const AUTH_COOKIE_NAME = "token";
const JWT_PERSISTENT_EXPIRY = "5d";
const JWT_SESSION_EXPIRY = "1d";
const AUTH_COOKIE_MAX_AGE_MS = 5 * 24 * 60 * 60 * 1000;

const ROLES = {
  STUDENT: "student",
  ALUMNI: "alumni",
  FACULTY: "faculty",
  ADMIN: "admin",
};

const PASSWORD_MIN_LENGTH = 8;
const FULL_NAME_MAX_LENGTH = 15;

const PROFILE_FIELD_LIMITS = {
  FULL_NAME: 100,
  LOCATION: 100,
  HEADLINE: 150,
  BIO: 1000,
  COMPANY: 150,
  JOB_TITLE: 150,
  EXPERIENCE_DESCRIPTION: 1000,
};

module.exports = {
  AUTH_COOKIE_NAME,
  JWT_PERSISTENT_EXPIRY,
  JWT_SESSION_EXPIRY,
  AUTH_COOKIE_MAX_AGE_MS,
  ROLES,
  PASSWORD_MIN_LENGTH,
  FULL_NAME_MAX_LENGTH,
  PROFILE_FIELD_LIMITS,
};
