const PAGINATION = {
  DEFAULT_PAGE: 1,
  ALUMNI_DIRECTORY_PAGE_SIZE: 6,
  ALUMNI_JOBS_PAGE_SIZE: 4,
  APPLICANT_PREVIEW_LIMIT: 3,
  DASHBOARD_REQUEST_LIMIT: 5,
  FEATURED_ALUMNI_DEFAULT_LIMIT: 4,
  FEATURED_ALUMNI_MAX_LIMIT: 12,
  JOBS_DEFAULT_PAGE_SIZE: 6,
  JOBS_MAX_PAGE_SIZE: 24,
  RECOMMENDED_MENTORS_LIMIT: 20,
  RECENT_ACTIVITY_QUERY_LIMIT: 5,
  RECENT_ACTIVITY_FEED_LIMIT: 6,
  STUDENT_DIRECTORY_PAGE_SIZE: 6,
  SUCCESS_STORIES_DEFAULT_PAGE_SIZE: 6,
  SUCCESS_STORIES_MAX_PAGE_SIZE: 24,
};

const STORY_CATEGORY_FILTER = {
  ALL: "All Categories",
};

module.exports = { PAGINATION, STORY_CATEGORY_FILTER };
